//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelioSOAP.Autos.Prerreserva
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreReservaAutoRequestDto", Namespace="http://rentaautos.ec/gestion")]
    public partial class PreReservaAutoRequestDto : object
    {
        
        private string IdVehiculoField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaFinField;
        
        private System.Nullable<int> DuracionHoldSegundosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdVehiculo
        {
            get
            {
                return this.IdVehiculoField;
            }
            set
            {
                this.IdVehiculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> DuracionHoldSegundos
        {
            get
            {
                return this.DuracionHoldSegundosField;
            }
            set
            {
                this.DuracionHoldSegundosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreReservaAutoResponseDto", Namespace="http://rentaautos.ec/gestion")]
    public partial class PreReservaAutoResponseDto : object
    {
        
        private string IdHoldField;
        
        private System.DateTime FechaExpiracionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdHold
        {
            get
            {
                return this.IdHoldField;
            }
            set
            {
                this.IdHoldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FechaExpiracion
        {
            get
            {
                return this.FechaExpiracionField;
            }
            set
            {
                this.FechaExpiracionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rentaautos.ec/gestion", ConfigurationName="TravelioSOAP.Autos.Prerreserva.WS_Integracion_ServicioSoap")]
    public interface WS_Integracion_ServicioSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentaautos.ec/gestion/CrearPreReservaAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoResponse> CrearPreReservaAutoAsync(TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearPreReservaAutoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearPreReservaAuto", Namespace="http://rentaautos.ec/gestion", Order=0)]
        public TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoRequestBody Body;
        
        public CrearPreReservaAutoRequest()
        {
        }
        
        public CrearPreReservaAutoRequest(TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentaautos.ec/gestion")]
    public partial class CrearPreReservaAutoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Prerreserva.PreReservaAutoRequestDto request;
        
        public CrearPreReservaAutoRequestBody()
        {
        }
        
        public CrearPreReservaAutoRequestBody(TravelioSOAP.Autos.Prerreserva.PreReservaAutoRequestDto request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearPreReservaAutoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearPreReservaAutoResponse", Namespace="http://rentaautos.ec/gestion", Order=0)]
        public TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoResponseBody Body;
        
        public CrearPreReservaAutoResponse()
        {
        }
        
        public CrearPreReservaAutoResponse(TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentaautos.ec/gestion")]
    public partial class CrearPreReservaAutoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TravelioSOAP.Autos.Prerreserva.PreReservaAutoResponseDto CrearPreReservaAutoResult;
        
        public CrearPreReservaAutoResponseBody()
        {
        }
        
        public CrearPreReservaAutoResponseBody(TravelioSOAP.Autos.Prerreserva.PreReservaAutoResponseDto CrearPreReservaAutoResult)
        {
            this.CrearPreReservaAutoResult = CrearPreReservaAutoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WS_Integracion_ServicioSoapChannel : TravelioSOAP.Autos.Prerreserva.WS_Integracion_ServicioSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_Integracion_ServicioSoapClient : System.ServiceModel.ClientBase<TravelioSOAP.Autos.Prerreserva.WS_Integracion_ServicioSoap>, TravelioSOAP.Autos.Prerreserva.WS_Integracion_ServicioSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_Integracion_ServicioSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_Integracion_ServicioSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_Integracion_ServicioSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Integracion_ServicioSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_Integracion_ServicioSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Integracion_ServicioSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_Integracion_ServicioSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Integracion_ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoResponse> TravelioSOAP.Autos.Prerreserva.WS_Integracion_ServicioSoap.CrearPreReservaAutoAsync(TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoRequest request)
        {
            return base.Channel.CrearPreReservaAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoResponse> CrearPreReservaAutoAsync(TravelioSOAP.Autos.Prerreserva.PreReservaAutoRequestDto request)
        {
            TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoRequest inValue = new TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoRequest();
            inValue.Body = new TravelioSOAP.Autos.Prerreserva.CrearPreReservaAutoRequestBody();
            inValue.Body.request = request;
            return ((TravelioSOAP.Autos.Prerreserva.WS_Integracion_ServicioSoap)(this)).CrearPreReservaAutoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_Integracion_ServicioSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_Integracion_ServicioSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_Integracion_ServicioSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_Integracion_Servicio.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_Integracion_ServicioSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://cuencautosrenta.runasp.net/WS_Integracion_Servicio.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_Integracion_ServicioSoap,
            
            WS_Integracion_ServicioSoap12,
        }
    }
}
